### ISSUE TITLE
Logging breaks on Crystal 0.34.0

### ISSUE THREAD

**Issue by lebogan** [arcage/crystal-email#57]
This is a known breaking change due to the Log module rewrite.

**Comment by arcage** [comment]
Thanks.

I will fix it in this week end.

**Comment by arcage** [comment]
I released v0.5.0 that fits the new `Log` module.

To do this, some change occured on the logging functions.

Could you check the new one?

**Comment by lebogan** [comment]
Thank you very much. Logging now works with email in my app. I will close?

**Comment by Nicolab** [comment]
Hello,

I have this issue with v0.6.0. 
v0.6.0 does not include this fix? https://github.com/arcage/crystal-email/blob/v0.6.0/src/email.cr#L2

**Comment by arcage** [comment]
v0.6.0 also supports new Log mechanism.
The new "log" module is **require**d at https://github.com/arcage/crystal-email/blob/v0.6.0/src/email/client.cr#L2 . 
But, I had forgotten the removing that line.

I will remove that line in next release ASAP.
Thank you pointed out it

And, at least in my environment, this issue had been solved after v0.5.0(also v0.6.0), and the compiler occurred no errors even if the `require "logger"` line exists.
Because, old Logger module is not removed in crystal 0.34.0 yet, but only in "Deprecated" status now.

Could you tell me the details of this issue in your environment?

**Comment by Nicolab** [comment]
Great, thanks :+1: 

> Because, old Logger module is not removed in crystal 0.34.0 yet, but only in "Deprecated" status now.
> Could you tell me the details of this issue in your environment?

Yes, there is hundreds lines of deprecation warning.

**Comment by arcage** [comment]
I released v0.6.1 that removes it.
Could you try it?

Deprecation warning will be occurred only when the old Logger object is used.
But, this shard uses no Logger object in the code base after v0.5.0.

I wonder why those warnings were occurred. 🤔

**Comment by Nicolab** [comment]
Indeed, sorry! After searching on the `Logger` instance and not on the name of the package (`logger`), it's Granite that causes this. :/ 

I have upgraded to 0.6.1. So it's totally made for crystal-email. :+1: 
Thank you for your reactivity, nice!
