### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by elrok123** [arcage/crystal-email#8]
The library seems fairly slow at sending emails. Is there a reason for this? Was expecting it to be incredibly fast considering it's crystal. Is there a way to speed this up? Currently writing a campaign generator in crystal and need an email library to handle auth and things, this library is perfect, bar the speed.

**Comment by arcage** [comment]
Thanks for your comment.
And, sorry for late reply.

This shard construct email message from scratch for every `send` method call. 

And, the construction process includes header checks, base64 encodings, and any other text handling.

If this shard cannot send message as fast you want, these processes may be too heavy.

As a matter of fact, I made this shard to send a few alert messages for system administrations. 

Therefore, I was not supposed to send a lot of mails at a time.

**Comment by bararchy** [comment]
What about adding Fibers and spawn as a way to handle multiple sends ?

**Comment by arcage** [comment]
Hi, @bararchy.

In my understanding, only one Fiber can work at the same time, even when a lot of Fibers exist. Therefore, I don't think that is able to solve the performance issue directly.

In the case that the network response is slow, multiple Fibers may be effective for that waiting time. 

IMO, because sending multiple emails simultaneously tends to make load to the SMTP server, I don't think the multiple sending is very good way.

**Comment by bararchy** [comment]
Well, maybe a "configure_burst" can be added to control the number of concurrent jobs when sending .

Also, when a Fiber reaches IO (Socket.write, Socket.read, File.write, etc..) another Fiber is able to run, so when you are essentially waiting for the remote SMTP to handle one email, you would be able to process more at the same time thous increasing speed

**Comment by bararchy** [comment]
P.S
In the near future Crystal will get a full parallelism support (multi CPU) based on Fibers, so you will get X Fibers running at the same time even when not on IO tasks

**Comment by arcage** [comment]
Thanks for instructive comments about Fibers.
And, I really have expectations for the parallelism support for the Crystal.

I will consider about the wrapping method to schedule the concurrent sending message to the multiple recipients by using Fibers.

**Comment by elrok123** [comment]
@arcage If you could increase the performance this could be a real player in the Crystal email libs, as there aren't many right now. You should definitely consider this if you're wanting this project to turn into something big :) Cheers for creating this lib anyway though, getting some use out of it, but it's not currently viable for me to use as a full alternative which upsets me as I want to transition a lot our software to Crystal, as I'm absolutely in love with the language, would be open to helping you improve this :)

**Comment by arcage** [comment]
Thanks again, @elrok123 .

This shard was originally made for just my use. I didn't think about performance well, because I have no tasks that require to send a lot of emails so speedy. Further, I had never implemented the codes required high performance so far. Although I don't know can I improve performance much as you want, I will try it as much as possible.

First, I’m considering whether email construction and email sending can be run concurrently.

**Comment by arcage** [comment]
Hi,

I have added concurrent sending support to this shard.

**Comment by arcage** [comment]
Because the concurrent sending is implemented, I'll close this once.
